/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import CONTROLADOR.Controlador_buscar_producto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author 19688016-K
 */
public class Buscar_producto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Buscar_producto
     */
    public Buscar_producto() {
        initComponents();
        CrearModelo2();
        Cargar_tabla();
    }
    Registrar_ingrediente gp;
    DefaultTableModel modelo2;
    String codigo;
    Ver_inventario v;
    Editar_ingrediente edi;
    private void CrearModelo2() {
        try {
            modelo2 = (new DefaultTableModel(
                    null, new String[]{
                        "Codigo", "Nombre",
                        "Cantidad", "Precio","Valor","Fecha"}) {
                Class[] types = new Class[]{
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false
                };

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            tabla1.setModel(modelo2);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error2");
        }
    }
    
    public String sendparameter(String rut2){
        String rut3 = rut2;
        return rut3;
    }
    public void Cargar_tabla(){
        Object o[]=null;
        Controlador_buscar_producto b = new Controlador_buscar_producto();
        for (int i = 0; i < b.tabla().size(); i++) {
            modelo2.addRow(o);
            modelo2.setValueAt(b.tabla().get(i).getCodigo_inventario(), i, 0);
            modelo2.setValueAt(b.tabla().get(i).getNombre(), i, 1);
            modelo2.setValueAt(b.tabla().get(i).getCantidad(), i, 2);
            modelo2.setValueAt(b.tabla().get(i).getPrecio_cu(), i, 3);
            modelo2.setValueAt(b.tabla().get(i).getValor_total_p(), i, 4);
            modelo2.setValueAt(b.tabla().get(i).getUlt_actualizacion(), i, 5);
        }
    }
    public void Limpiar_tablla(){
        while(modelo2.getRowCount()>0){
            for (int i = 0; i < modelo2.getRowCount(); i++) {
                modelo2.removeRow(i);
            }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        Editar = new javax.swing.JButton();
        ver = new javax.swing.JButton();
        com = new javax.swing.JComboBox<>();
        eliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar producto");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Buscar por codigo");

        jLabel4.setText("Buscar por nombre");

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Productos");

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nombre:");

        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        ver.setText("Ver");
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });

        com.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Unidades", "Kilos", "Litros" }));
        com.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comMouseClicked(evt);
            }
        });
        com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        jLabel6.setText("Codigo seleccionado:");

        txtcod.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(com, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(14, 14, 14)
                                        .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(ver, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(com, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
        if (edi== null || edi.isClosed()) {
            edi = new Editar_ingrediente();

            edi.setVisible(true);
            getParent().add(edi);
        } else {
            JOptionPane.showMessageDialog(null, "Esta ventana ya esta abierta", "Error #01", JOptionPane.WARNING_MESSAGE);
        }
        
            
    }//GEN-LAST:event_EditarActionPerformed

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
        // TODO add your handling code here:
        if (v == null || v.isClosed()) {
            v = new Ver_inventario();

            v.setVisible(true);
            getParent().add(v);
        } else {
            JOptionPane.showMessageDialog(null, "Esta ventana ya esta abierta", "Error #01", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_verActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        String respuesta = JOptionPane.showInputDialog("El codigo");
        Controlador_buscar_producto b = new Controlador_buscar_producto();
        b.Eliminar(respuesta);
        Limpiar_tablla();
        Cargar_tabla();
    }//GEN-LAST:event_eliminarActionPerformed

    private void tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo =(DefaultTableModel) tabla1.getModel();
        int i =tabla1.getSelectedRow();
        codigo = modelo.getValueAt(i, 0).toString();
        
        txtcod.setText(codigo);
    }//GEN-LAST:event_tabla1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String b_cod=cod.getText();
        
        Limpiar_tablla();
        
        Object o[]=null;
        Controlador_buscar_producto b = new Controlador_buscar_producto();
        for (int i = 0; i < b.Buscar_r(b_cod).size(); i++) {
            modelo2.addRow(o);
            modelo2.setValueAt(b.Buscar_r(b_cod).get(i).getCodigo_inventario(), i, 0);
            modelo2.setValueAt(b.Buscar_r(b_cod).get(i).getNombre(), i, 1);
            modelo2.setValueAt(b.Buscar_r(b_cod).get(i).getCantidad(), i, 2);
            modelo2.setValueAt(b.Buscar_r(b_cod).get(i).getPrecio_cu(), i, 3);
            modelo2.setValueAt(b.Buscar_r(b_cod).get(i).getValor_total_p(), i, 4);
            modelo2.setValueAt(b.Buscar_r(b_cod).get(i).getUlt_actualizacion(), i, 5);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String nom=txtnom.getText();
        
        Limpiar_tablla();
        
        Object o[]=null;
        Controlador_buscar_producto b = new Controlador_buscar_producto();
        for (int i = 0; i < b.Buscar_n(nom).size(); i++) {
            modelo2.addRow(o);
            modelo2.setValueAt(b.Buscar_n(nom).get(i).getCodigo_inventario(), i, 0);
            modelo2.setValueAt(b.Buscar_n(nom).get(i).getNombre(), i, 1);
            modelo2.setValueAt(b.Buscar_n(nom).get(i).getCantidad(), i, 2);
            modelo2.setValueAt(b.Buscar_n(nom).get(i).getPrecio_cu(), i, 3);
            modelo2.setValueAt(b.Buscar_n(nom).get(i).getValor_total_p(), i, 4);
            modelo2.setValueAt(b.Buscar_n(nom).get(i).getUlt_actualizacion(), i, 5);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_comMouseClicked

    private void comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comActionPerformed
        // TODO add your handling code here:
        if (com.getSelectedItem().equals("Todas")) {
            Limpiar_tablla();
            Cargar_tabla();
        }
        if (com.getSelectedItem().equals("Unidades")) {
            Limpiar_tablla();
            Object o[] = null;
            Controlador_buscar_producto b = new Controlador_buscar_producto();
            for (int i = 0; i < b.tabla_u().size(); i++) {
                modelo2.addRow(o);
                modelo2.setValueAt(b.tabla_u().get(i).getCodigo_inventario(), i, 0);
                modelo2.setValueAt(b.tabla_u().get(i).getNombre(), i, 1);
                modelo2.setValueAt(b.tabla_u().get(i).getCantidad(), i, 2);
                modelo2.setValueAt(b.tabla_u().get(i).getPrecio_cu(), i, 3);
                modelo2.setValueAt(b.tabla_u().get(i).getValor_total_p(), i, 4);
                modelo2.setValueAt(b.tabla_u().get(i).getUlt_actualizacion(), i, 5);
            }

        }
        if (com.getSelectedItem().equals("Kilos")) {
            Limpiar_tablla();
            Object o[] = null;
            Controlador_buscar_producto b = new Controlador_buscar_producto();
            for (int i = 0; i < b.tabla_k().size(); i++) {
                modelo2.addRow(o);
                modelo2.setValueAt(b.tabla_k().get(i).getCodigo_inventario(), i, 0);
                modelo2.setValueAt(b.tabla_k().get(i).getNombre(), i, 1);
                modelo2.setValueAt(b.tabla_k().get(i).getCantidad(), i, 2);
                modelo2.setValueAt(b.tabla_k().get(i).getPrecio_cu(), i, 3);
                modelo2.setValueAt(b.tabla_k().get(i).getValor_total_p(), i, 4);
                modelo2.setValueAt(b.tabla_k().get(i).getUlt_actualizacion(), i, 5);
            }
        }
        if (com.getSelectedItem().equals("Litros")) {
            Limpiar_tablla();
            Object o[] = null;
            Controlador_buscar_producto b = new Controlador_buscar_producto();
            for (int i = 0; i < b.tabla_l().size(); i++) {
                modelo2.addRow(o);
                modelo2.setValueAt(b.tabla_l().get(i).getCodigo_inventario(), i, 0);
                modelo2.setValueAt(b.tabla_l().get(i).getNombre(), i, 1);
                modelo2.setValueAt(b.tabla_l().get(i).getCantidad(), i, 2);
                modelo2.setValueAt(b.tabla_l().get(i).getPrecio_cu(), i, 3);
                modelo2.setValueAt(b.tabla_l().get(i).getValor_total_p(), i, 4);
                modelo2.setValueAt(b.tabla_l().get(i).getUlt_actualizacion(), i, 5);
            }
        }
    }//GEN-LAST:event_comActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editar;
    private javax.swing.JTextField cod;
    private javax.swing.JComboBox<String> com;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabla1;
    public static javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtnom;
    private javax.swing.JButton ver;
    // End of variables declaration//GEN-END:variables
}
